### PR TITLE
Icon if text is empty + clear button in entry

### PR DESCRIPTION
**Pull request by kra-mo**
Hi, it seems that I made the same mistake as you and missed that there were actually two other similar extensions before developing my own. 😅
In light of that, I figured I would contribute to one of the existing projects.

### CODE REVIEW

**Comment by jancborchardt** [comment]
Yeah good point @kra-mo! The first published extension is https://extensions.gnome.org/extension/5072/one-thing/ by @dantehemerson. As it is already published, installed by people and looks nice I would say it’s best we all collaborate on that one if it’s ok with the author. :)

What do you think @PRATAP-KUMAR @dantehemerson?

**Comment by jancborchardt** [comment]
Thanks a lot for your contribution though @kra-mo! :) Sorry for noticing it so late – I sent you a mail too just now

**Comment by dante-globant** [comment]
@jancborchardt @kra-mo I agree wih you guys. I think that this and the show on lockscreen features are useful. 
It would be great if we add that functionalities to the extension.

@jancborchardt I think I can also transfer the reporitory to this organization if you prefer.

**Comment by jancborchardt** [comment]
> I think I can also transfer the reporitory to this organization if you prefer.

Sure, nice idea, then it's more of a community project :) added both @kra-mo and you to the organization. You can also add other contributors from the repo there.

**Comment by jancborchardt** [comment]
> I think I can also transfer the reporitory to this organization if you prefer.

@dante-calderon Sure, nice idea, then it's more of a community project :) added both @kra-mo and you to the organization. You can also add other contributors from the repo there.

**Pull request closed without merging**
